### ISSUE TITLE
Shadow issues

### ISSUE THREAD

**Issue by VanitasCloud** [emoose/NieRAutomata-LodMod#10]
More like an issue it's a question: Is there any way to fix these shadows with LodMod.ini config? https://imgur.com/a/XnLBJ2j

Here's a video showing the issue (that's also in the game without LodMod) https://drive.google.com/file/d/1sSsdC7scsoj0j5DNiu43htqG5IA-CBD2/view?usp=sharing

**Comment by emoose** [comment]
IIRC it's an issue with the way game does cascaded shadow mapping, tried a bunch of things to improve it but didn't really manage to make a one-size-fits-all fix for it unfortunately (game uses different CSM parameters for different levels, so improving one area would make another one look worse...)

I think increasing `ShadowDistanceMultiplier` (and setting `ShadowDistanceMinimum` to 0 to disable that) helped in that city area though, but like mentioned it might end up making some other areas look worse, never managed to come up with a way to set things per-area sadly.
