### ISSUE TITLE
Building from source code

### ISSUE THREAD

**Issue by BigheadSMZ** [emoose/NieRAutomata-LodMod#16]
So I've managed to actually encode H.264 into USM successfully, and I've been interested in trying to build this project from source. I noticed for obvious reasons the repo does not include the following files:

- crimana_decoder_h264_mft.obj
- crimv_decoder_v264mft.obj
- crimvply_decoder_v264mft.obj
- criv264mft_lib.obj

It took me awhile to track down exactly what I was looking for, and found this post which put me on the right track.
https://steamcommunity.com/app/524220/discussions/0/5197701062328187336/?ctp=23#c3037102935227730358

I copied those files into the repo, built the source code to a DLL successfully, but H.264 movies do not play. This also leads to a bug in the intro where 2B smashes through the wall and flies over an endless ocean.

The latest SDK I managed to find was v2.19.03, and this comment mentions v.2.19.15. I opened up **cri_mana_pcx86.lib** with 7z to extract the files from the list above. I am assuming the x64 versions are needed over the x86 versions. So now I'm curious on where to go from here, or rather, what my mistake was. My assumptions are as follows:

- The files from v2.19.03 will not work, and I need to locate v2.19.15 (which has been.. not successful)
- I am extracting these incorrectly. I don't know anything about obj/lib files, and extracting with 7z seems like maybe I'm doing it wrong.
- Migrating to VS2022, maybe something is lost in translation?

I was just wondering if anyone can point me in the right direction of how to fix this issue. The compiled DLL is also smaller: 328 KB vs 335KB, making me assume something isn't working correctly. Any help would be appreciated.

**Comment by emoose** [comment]
Think the v2.19.15 is the ver of the mana lib itself, which might be different to the actual SDK ver, if you look in crimana_global.obj there should be a string `CRI Mana/PCx64 Ver.XX` which says the version of it.

Looks like files I used were from cri_ue4_1.28.00.02 pack, cri_mana_pcx64.lib from there should have them, extracting with 7z should work fine.

VS2022 could be an issue though, IIRC there were some recent runtime changes in one of the VS2022 updates that could have broke compatibility with older libs like this, might need to locate a newer criware SDK instead :/

**Comment by BigheadSMZ** [comment]
Looks like this one is definitely older.
CRI Mana/PCx64 Ver.2.18.00 
Build:Feb 22 2019 16:17:17
I'll track down the newer ones rebuild and test.
