### ISSUE TITLE
DLL chainloading on v0.76.x

### ISSUE THREAD

**Issue by Kyhze** [emoose/NieRAutomata-LodMod#7]
Looks like using the wrapper to chainload DLLs no longer works on versions v0.76/0.76.1
Tested with NAIOM named as NAIOM.dll, it gets chainloaded correctly on any LodMod version prior to 0.76. 
I haven't tested renaming NAIOM to something else, nor have I tested to chainload other DLLs.

**Comment by emoose** [comment]
Hmm, is your LodMod DLL named as dinput8.dll? Seems to work fine with that, unfortunately looks like NAIOM only wraps dinput8, so LM would also have to be used in dinput8-wrapping mode.

If it worked in 0.75 that was probably by mistake, this way of wrapping the chainloaded DLL was how the chainloading stuff was intended... but I could maybe add a switch so it can load in plugins without wrapping though, wouldn't work with every DLL mod but might help with NAIOM.

(it's too bad NAIOM dev doesn't wrap all the other stuff like xinput/dxgi/etc... would give people more options for naming things... my [proxy.cpp](https://github.com/emoose/NieRAutomata-LodMod/blob/master/Automata-LodMod/proxy.cpp) wrapper code for all those DLLs is always open-source for anyone to use :)

**Comment by Kyhze** [comment]
Yes, I have Lod named as dinput8.dll, since NAIOM indeed requires to be loaded as dinput8. 
I forgot to mention but here's my setup (note that everything is in the game folder):

-LodMod named as dinput8.dll
-NAIOM named NAIOM.dll
-Wrapper enabled in LodMod.ini (LoadLibrary = NAIOM.dll)

I also use SpecialK and ReShade:
-SK named dxgi.dll (+dxgi.ini for its configuration file)
-ReShade64.dll loaded as a SK plug-in in dxgi.ini 

With this setup, everything works as intended while using Lod <0.76 (i.e.: SK works, Reshade works, Lod works, but NAIOM doesn't get loaded). 

If I replace Lod with any other version prior to 0.76, (always renamed as dinput8.dll), then NAIOM gets loaded. 

To better illustrate the setup:

![Sans titre](https://user-images.githubusercontent.com/67647288/130570041-2ad9467e-cff4-4dbb-9588-314b5d97e4d5.png)

I'll enable Lod debug log and compare the output from v0.76 and <v.0.76 to see if I can find anything relevant :)

**Comment by Kyhze** [comment]
Here are the debug logs from 0.76.1 and 0.75.1 (I deleted everything past the "LodMod init complete!" line to make it much shorter):

0.76.1:

```
NieR Automata LodMod 0.76.1 - by emoose
LodMod module name: DINPUT8.dll
Detected game type: Steam/Win10
Wrapping DLL from NAIOM.dll
Loaded INI from C:\Program Files (x86)\Steam\steamapps\common\NieRAutomata\LodMod.ini

Settings:
 LODMultiplier: 0.000000
 AOMultiplierWidth: 1.500000
 AOMultiplierHeight: 1.500000
 ShadowDistanceMultiplier: 2.000000
 ShadowDistanceMinimum: 0.000000
 ShadowDistanceMaximum: 0.000000
 ShadowResolution: 8192
 ShadowFilterStrengthBias: 0.000000
 ShadowFilterStrengthMinimum: 0.000000
 ShadowFilterStrengthMaximum: 0.000000
 DisableManualCulling: true
 CommunicationScreenResolution: 256
 HQMapSlots: 7

Shadow quadrant size: 4096
ShadowBuffSizeBits: 4
ShadowResNumBits: 12
Shadow resolution patched to 8192x8192.
 SoftFilteredModels: 42 filters
 HardFilteredModels: 14 filters

LodMod init complete!
```

0.75.1:

```
NieR Automata LodMod 0.75.1 - by emoose
LodMod module name: DINPUT8.dll
Detected game type: Steam/Win10
Wrapping DLL from NAIOM.dll
Loaded INI from C:\Program Files (x86)\Steam\steamapps\common\NieRAutomata\LodMod.ini

Settings:
 LODMultiplier: 0.000000
 AOMultiplierWidth: 1.500000
 AOMultiplierHeight: 1.500000
 ShadowDistanceMultiplier: 2.000000
 ShadowDistanceMinimum: 0.000000
 ShadowDistanceMaximum: 0.000000
 ShadowResolution: 8192
 ShadowFilterStrengthBias: 0.000000
 ShadowFilterStrengthMinimum: 0.000000
 ShadowFilterStrengthMaximum: 0.000000
 DisableManualCulling: true
 CommunicationScreenResolution: 256
 HQMapSlots: 7

 SoftFilteredModels: 42 filters
 HardFilteredModels: 14 filters

Hooks complete!
Shadow quadrant size: 4096
ShadowBuffSizeBits: 4
ShadowResNumBits: 12
Shadow resolution patched to 8192x8192.

LodMod init complete!
```
The only real difference I'm seeing is that 0.75.1 says "Hooks complete!" while 0.76.1 doesn't, but I'm not even sure it's referring to DLL wrapping. (I admit I didn't test without wrapping to see if this changes)

Perhaps this would be useful for debugging as well, here is my LodMod.ini (renamed as .txt as github doesn't support ini files in comments...):

[LodMod.txt](https://github.com/emoose/NieRAutomata-LodMod/files/7037210/LodMod.txt)

**Comment by emoose** [comment]
Ahhh realized what it is, I moved the code that reads the INI file to after the game had decrypted itself, since that code tries calling into game to find out save folder, but the chainloading stuff happens almost near the beginning, so it hadn't actually loaded in the DLL name to chainload yet :X

I'll have a fix up in a sec, gonna see if I can reimpl. that save folder function instead of calling into the game.

**Comment by emoose** [comment]
Uploaded v0.76.2 to https://github.com/emoose/NieRAutomata-LodMod/releases/tag/v0.76.2, hopefully this'll help with this issue for you :)

**Comment by Kyhze** [comment]
Wow that was fast! 

I tested out v0.76.2 and I can confirm everything works fine now! :D 

Thank you for all the great work you do for us! :)
